<?php

namespace Database\Seeders;

use App\Models\Profession;
use App\Models\ScrapingKeyword;
use Illuminate\Database\Seeder;

class ExtractionDataSeeder extends Seeder
{
    public function run(): void
    {
        $keywords = [
            'Si cerca',
            'Si cercano',
            'Profili ricercati',
            'Requisiti',
            'Personaggi',
            'Ruoli',
            'Casting per',
            'Stiamo cercando',
        ];

        foreach ($keywords as $keyword) {
            ScrapingKeyword::updateOrCreate(['keyword' => $keyword]);
        }

        $professions = "AMMINISTRAZIONE;AMMINISTRAZIONE;FCRC
AMMINISTRAZIONE;AIUTO AMMINISTRATORE;FCRC
AMMINISTRAZIONE;CASSIERE;FCRC
AMMINISTRAZIONE;PRODUCTION ACCOUNTANT;INTEGRATA
CASTING;CASTING DIRECTOR;FCRC
CASTING;CASTING DIRECTOR (UIC);FCRC
CASTING;ASSISTENTE AL CASTING;FCRC
CASTING;CASTING DIRECTOR FIGURAZIONI;INTEGRATA (CROWD)
CASTING;CAPOGRUPPO;INTEGRATA (CROWD)
COSTUMI;COSTUMISTA;FCRC
COSTUMI;AIUTO COSTUMISTA;FCRC
COSTUMI;ASSISTENTE COSTUMISTA;FCRC
COSTUMI;SARTO;FCRC
COSTUMI;KEY COSTUMER / GESTIONE MAGAZZINO;INTEGRATA
ELETTRICISTI;CAPOSQUADRA (GAFFER);FCRC
ELETTRICISTI;ELETTRICISTA (SPARK);FCRC
ELETTRICISTI;OPERATORE CONSOLE LUCI;INTEGRATA
FOTOGRAFIA;DIRETTORE DELLA FOTOGRAFIA;FCRC
FOTOGRAFIA;OPERATORE DI RIPRESA (35/16 mm);FCRC
FOTOGRAFIA;OPERATORE VIDEO;FCRC
FOTOGRAFIA;OPERATORE STEADYCAM;FCRC
FOTOGRAFIA;OPERATORE LUCI;FCRC
FOTOGRAFIA;OPERATORE SUBACQUEO;FCRC
FOTOGRAFIA;ASSISTENTE OPERATORE (FOCUS PULLER);FCRC
FOTOGRAFIA;VIDEO ASSIST;FCRC
FOTOGRAFIA;FOTOGRAFO DI SCENA;FCRC
FOTOGRAFIA;FOTOGRAFO;FCRC
FOTOGRAFIA;REPORTER;FCRC
FOTOGRAFIA;D.I.T. (DIGITAL IMAGING TECHNICIAN);INTEGRATA
FOTOGRAFIA;DATA MANAGER;INTEGRATA
FOTOGRAFIA;PILOTA DRONE (APR);INTEGRATA
FOTOGRAFIA;SECONDO ASSISTENTE OPERATORE (LOADER);INTEGRATA
MACCHINISTI;CAPOSQUADRA (KEY GRIP);FCRC
MACCHINISTI;MACCHINISTA;FCRC
MACCHINISTI;MACCHINISTA TEATRO;FCRC
MONTAGGIO;MONTATORE;FCRC
MONTAGGIO;ASSISTENTE AL MONTAGGIO;FCRC
MONTAGGIO;COLORIST;INTEGRATA
POST-PRODUZIONE;GRAFICA E ANIMAZIONE;FCRC
POST-PRODUZIONE;EFFETTI VISIVI E COMPOSITING;FCRC
POST-PRODUZIONE;VFX SUPERVISOR;INTEGRATA
POST-PRODUZIONE;MOTION DESIGNER;INTEGRATA
POST-PRODUZIONE AUDIO;COMPOSITORE;FCRC
POST-PRODUZIONE AUDIO;SOUND DESIGNER;INTEGRATA
POST-PRODUZIONE AUDIO;RUMORISTA (FOLEY ARTIST);INTEGRATA
POST-PRODUZIONE AUDIO;MONTATORE DEL SUONO;INTEGRATA
PRODUZIONE;PRODUTTORE;FCRC
PRODUZIONE;PRODUTTORE ESECUTIVO;FCRC
PRODUZIONE;ORGANIZZATORE DI PRODUZIONE;FCRC
PRODUZIONE;DIRETTORE di PRODUZIONE;FCRC
PRODUZIONE;ISPETTORE DI PRODUZIONE;FCRC
PRODUZIONE;LOCATION MANAGER;FCRC
PRODUZIONE;LOCATION SCOUT;FCRC
PRODUZIONE;SEGRETARIO DI PRODUZIONE;FCRC
PRODUZIONE;COORDINATORE DI PRODUZIONE;FCRC
PRODUZIONE;ASSISTENTE DI PRODUZIONE;FCRC
PRODUZIONE;ASSISTENTE AL PRODUTTORE;FCRC
PRODUZIONE;AIUTO SEGRETARIO DI PROD./ RUNNER;FCRC
PRODUZIONE;AUTISTA;FCRC
PRODUZIONE;UNIT MANAGER;INTEGRATA
PRODUZIONE;GREEN MANAGER / ECO-CONSULTANT;INTEGRATA
PRODUZIONE;TRAVEL COORDINATOR;INTEGRATA
REGIA;REGISTA;FCRC
REGIA;FILM-MAKER INDIPENDENTE;FCRC
REGIA;AIUTO REGISTA;FCRC
REGIA;ASSISTENTE ALLA REGIA;FCRC
REGIA;SEGRETARIO DI EDIZIONE (SCRIPT SUPERVISOR);FCRC
REGIA;ACTOR'S COACH;FCRC
REGIA;INTIMACY COORDINATOR;INTEGRATA
REGIA;CROWD MARSHALL (GESTIONE COMPARSE);INTEGRATA
REGIA;AIUTO REGISTA ALLE FIGURAZIONI;INTEGRATA (CROWD)
REGIA;CHAPERONE (TUTELA MINORI);INTEGRATA
SCENEGGIATURA;SCENEGGIATORE;FCRC
SCENEGGIATURA;SCRIPT COORDINATOR;FCRC
SCENEGGIATURA;DIALOGHISTA;FCRC
SCENEGGIATURA;STORYBOARD ARTIST;INTEGRATA
SCENOGRAFIA;SCENOGRAFO;FCRC
SCENOGRAFIA;ARREDATORE;FCRC
SCENOGRAFIA;EFFETTI SPECIALI (SFX);FCRC
SCENOGRAFIA;ASSISTENTE SCENOGRAFO;FCRC
SCENOGRAFIA;AIUTO SCENOGRAFO;FCRC
SCENOGRAFIA;ATTREZZISTA (PROP MASTER);FCRC
SCENOGRAFIA;AIUTO ATTREZZISTA;FCRC
SCENOGRAFIA;REALIZZAZIONI SCENOGRAFICHE;FCRC
SCENOGRAFIA;MANOVALE;FCRC
SCENOGRAFIA;SET DECORATOR;INTEGRATA
SCENOGRAFIA;BUYER;INTEGRATA
SCENOGRAFIA;CAPO COSTRUTTORE;INTEGRATA
SCENOGRAFIA;PITTORE DI SCENA;INTEGRATA
STUNT;STUNT COORDINATOR;FCRC
STUNT;STUNT;FCRC
STUNT;MAESTRO;FCRC";

        $lines = explode("\n", $professions);
        foreach ($lines as $line) {
            $line = trim($line);
            if (empty($line)) continue;
            
            $parts = explode(';', $line);
            if (count($parts) < 2) continue;
            
            Profession::updateOrCreate(
                ['area' => $parts[0], 'title' => $parts[1]],
                ['origin' => $parts[2] ?? null]
            );
        }
    }
}
